### ISSUE TITLE
clean code

### ISSUE THREAD

**Issue by geeksesi** [AmiiirCom/bad-words-remover-telegram-bot#4]
please use sneak_case for variable and functions.
first upper case is just standard for classes.
please read this clean code law for php [php-psr](https://github.com/php-fig/fig-standards/tree/master/accepted)

also we tried to make a persian version here : [persian php-psr](https://github.com/FarhadHP/php-psr)

**Comment by geeksesi** [comment]
please fix names i will work on database.

**Comment by AmiiirCom** [comment]
> please fix names i will work on database.

I fix it

**Comment by geeksesi** [comment]
do you use any format fixer for php ?
i'm using this on vscode [php intelephense](https://github.com/bmewburn/vscode-intelephense)
and i just see you chaged my code with "Clean code" comment just because this alignment.
it's will be make conflict. i just will make your project database.
don't commit some file who phpstorm aligned them ( and you did not changed it )
wait fix align all of them after my work finished. :)
